title: 宇浩·星陳
description: 繁简通打·极致低重·全汉字输入
theme: just-the-docs

url: https://zhuyuhao.com/yustar

aux_links:
  点击加入QQ群: https://jq.qq.com/?_wv=1027&k=2OYDP4Tk
  点击加入Telegram群: https://t.me/yustarim

# External navigation links
nav_external_links:
  - title: 拆分查询
    url: https://zhuyuhao.com/yustar/star/chaifen
    hide_icon: false # set to true to hide the external link icon - defaults to false

markdown: kramdown
math: katex
layout: katex

# kramdown:
#   syntax_highlighter_opts:
#     block:
#       line_numbers: false

callouts:
  highlight:
    color: yellow
  important:
    title: 重要
    color: blue
  example:
    # title: 举例
    color: green
  note:
    title: 备注
    color: purple
  warning:
    title: 提醒
    color: red